export const PROJECTS = [
  // ── Live / Launched (strategic order) ──
  {
    year: 'Dec 2025',
    status: 'live',
    tag: 'Law Practice',
    title: 'Hoag Law.ai',
    domain: 'hoaglaw.ai',
    href: 'https://hoaglaw.ai',
    color: '#FF3A00',
    ogImage: 'https://hoaglaw.ai/images/og-default.png',
    desc: "Fractional GC for AI and SaaS startups at a flat $10K/month. No hourly billing, no surprises. I embed with your team the way a founder would — because I've been one.",
  },
  {
    year: 'Nov 2025',
    status: 'live',
    tag: 'Bar Leadership',
    title: 'BHBA AI and the Law',
    domain: 'bhba.org',
    href: 'https://bhba.org/sections/ai-and-the-law/',
    color: '#1A3BFF',
    ogImage: '/bhbalogo.png',
    ogFit: 'cover',
    ogPos: '60% 65%',
    ogScale: 1.12,
    desc: "Inaugural Chair of the Beverly Hills Bar Association's AI and the Law section. Shaping how the legal profession engages with AI — through CLEs, publications, and policy.",
  },
  {
    year: 'Mar 2026',
    status: 'live',
    tag: 'Fintech · Community',
    title: 'Finnly.ai',
    domain: 'finnly.ai',
    href: 'https://finnly.ai',
    color: '#E8700A',
    ogImage: 'https://finnly.ai/finnly-logo.png',
    desc: 'Platform for fractional finance professionals — CFOs, controllers, and operators who work across multiple companies.',
  },
  {
    year: 'Feb 2026',
    status: 'launched',
    tag: 'AI Advisory',
    title: 'Skyriven.ai',
    domain: 'skyriven.ai',
    href: 'https://skyriven.ai',
    color: '#0A192F',
    ogImage: 'https://skyriven.ai/og-image.png',
    desc: "AI strategy, rapid prototyping, and vibe-coded product development. We build fast and think hard about what we're building.",
  },
  {
    year: 'Mar 2026',
    status: 'live',
    tag: 'Developer Tools',
    title: 'Orbital',
    domain: 'getorbital.dev',
    href: 'https://getorbital.dev',
    color: '#00AACC',
    ogImage: 'https://getorbital.dev/homepage_dashboard_screenshot.png',
    desc: 'Subscription management and app launcher dashboard for developers. Because SaaS sprawl is a real problem.',
  },
  {
    year: 'Mar 2026',
    status: 'launched',
    tag: 'iOS · Eye Tracking',
    title: 'Saccade',
    domain: 'saccadeapp.com',
    href: 'https://saccadeapp.com',
    color: '#D4A800',
    ogImage: 'https://saccadeapp.com/img/og-image.png',
    desc: 'A/B testing with your eyes. Upload image variants and Saccade uses real-time gaze tracking to rank which ones you naturally look at longer. 100% on-device, no account needed.',
  },
  {
    year: 'Jan 2026',
    status: 'live',
    tag: 'iOS · Civic Tech',
    title: 'FloodRoute',
    domain: 'floodroute.com',
    href: 'https://floodroute.com',
    color: '#2E9E8F',
    ogImage: 'https://floodroute.com/assets/images/card.jpg',
    ogFit: 'cover',
    desc: 'Real-time flood and high-tide alerts with crowdsourced reporting. Built in Swift. Covers 16 US regions.',
  },
  {
    year: 'Jul 2025',
    status: 'live',
    tag: 'Content Discovery',
    title: 'Scribefully',
    domain: 'scribefully.com',
    href: 'https://scribefully.com',
    color: '#1A5CFF',
    ogImage: 'https://scribefully.com/scribefully_icon_v3.png',
    ogFit: 'cover',
    desc: 'A platform for finding and following the people worth reading.',
  },
  // ── Coming Soon ──
  {
    year: 'Mar 2026',
    status: 'soon',
    tag: 'Consumer AI',
    title: 'Ask Nonna',
    domain: 'asknonna.app',
    href: 'https://asknonna.app',
    color: '#FF3A00',
    desc: 'Your AI kitchen companion with old-world culinary wisdom. Because grandmothers knew things.',
  },
  {
    year: '2026',
    status: null,
    tag: '2026 · Coming soon',
    title: '[ redacted ]',
    domain: null,
    href: null,
    color: '#8FCC00',
    desc: "Something's cooking. More soon.",
  },
  {
    year: '2026',
    status: null,
    tag: '2026 · Coming soon',
    title: '[ redacted ]',
    domain: null,
    href: null,
    color: '#CC0066',
    desc: "Something's cooking. More soon.",
  },
]

export const PODCAST_URL = 'https://podcasts.apple.com/us/podcast/marc-hoag-ai-law-pod-formerly-autonomous-cars-with-marc-hoag/id1353975287'

export const MARQUEE_WORDS = [
  'Builder', 'Lawyer', 'Founder', 'Vibe Coder',
  'Podcaster', 'Section Chair', 'Maker', 'Thinker',
]

export const MARQUEE_COLORS = [
  '#FF3A00', '#1A3BFF', '#8FCC00', '#CC0066', '#00AACC', '#D4A800',
]

export const BADGE_LABELS = {
  live: 'Live',
  launched: 'Just launched',
  soon: 'Coming soon',
}
